### ISSUE TITLE
Why is Input Node not "Cast"? Is there a difference between "Mul" and "Mul:0"?

### ISSUE THREAD

**Issue by dakshj** [googlecodelabs/tensorflow-for-poets-2#1]
Even though TensorFlow For Poets 2 does not warrant the running of "strip_unused.py", the app still runs with a retrained+optimized+quantized model.

However, during the optimization step to skip the "DecodeJpeg" node, we redirected the input node to "Cast". But the app works only when the input node specified is "Mul" or "Mul:0".

My first question is, why is the input node not "Cast"?

My second question is, what is the actual difference between "Mul" and "Mul:0" in [ClassifierActivity.java](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/android/src/org/tensorflow/demo/ClassifierActivity.java#L64), since both of these input nodes make the app work with the retrained+optimized+quantized model.

**Comment by vladkarpman** [comment]
Also don't know

**Comment by vladkarpman** [comment]
I also have the same questions. It should be clarified

**Comment by MarkDaoust** [comment]
There are a few questions here.

The difference between "mul" and "mul:0" is that "mul" is the name of the operation, and "mul:0" is the name of a tensor, output "0" of the operation. Only tensors have values, not operations. But, If you ask tensorflow for the value of an operation, it assumes you want the value of output "0". So they are equivalent.
------------------------------
The app is feeding to the mul node, [see diagram](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2/#4), because it is doing the resize and centering in the app. I think that code is included for compatibility with other networks.

But if you want to feed directly to the cast node, I think you would just need to skip the java code that implements those operations.

The [normalization and conversion to float is done here](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/01e5a68183d158c5b04944e8f44674eeaa91f679/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java#L134), and it looks like [the cropping is happening around here](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/01e5a68183d158c5b04944e8f44674eeaa91f679/android/src/org/tensorflow/demo/ClassifierActivity.java#L214).

Just remember that if you're feeding to "Cast" that's the output of cast you're feeding to. So you at least need to keep the conversion to float.

Give it a shot!
Send a PR if you can get it to work, maybe it will be more efficient.

**Comment by bis-carbon** [comment]
Hello everyone,
I have a question. Which is I used MobileNets for classification purpose and implemented it on android and PC, the problem is I get different prediction values on android and PC (linux) for the same picture and model. The difference is on average magnitude of 5%.   What cause this difference ?

**Comment by MarkDaoust** [comment]
I've recently upgraded this repo to use [MobileNets](https://arxiv.org/abs/1704.04861) so the Mul/Cast nodes no-longer exists.

@bis-carbon I don't know what it is, consider investigating to narrow it down (any idea which op?), and if you figure it out, maybe send a bug to the tensorflow repo.
